<a href="https://colab.research.google.com/github/aliyheva/MyDataScience/blob/main/Excersises_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**GITHUB TASKS**

In [ ]:
import numpy as np
arr_1D=np.array([1,2,3,4,5])
arr_1D


array([1, 2, 3, 4, 5])

In [ ]:
arr_2D=np.array([[1,2,3],[4,5,6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_3D=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr_1D.shape,arr_1D.ndim,arr_1D.size,arr_1D.dtype

((5,), 1, 5, dtype('int64'))

In [ ]:
arr_2D.shape,arr_2D.ndim,arr_2D.size,arr_2D.dtype

((2, 3), 2, 6, dtype('int64'))

In [ ]:
arr_3D.shape,arr_3D.ndim,arr_3D.size,arr_3D.dtype

((2, 2, 3), 3, 12, dtype('int64'))

In [ ]:
import pandas as pd
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
arr=np.random.randint(0,10,size=(7,2))
arr

array([[1, 3],
       [9, 2],
       [2, 3],
       [9, 8],
       [7, 5],
       [0, 5],
       [8, 4]])

In [ ]:
arr=np.random.uniform(0,1,size=(3,5))
arr

array([[0.65528218, 0.20300854, 0.6597558 , 0.34820938, 0.64082443],
       [0.83013128, 0.01259985, 0.63422489, 0.93129869, 0.72592232],
       [0.57512189, 0.43393373, 0.2002187 , 0.55955722, 0.9430997 ]])

In [ ]:
arr=np.random.seed(42)
arr=np.random.randint(0,10,size=(4,6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
arr=np.random.randint(1,10,size=(3,5))
np.unique(arr)

array([1, 2, 3, 5, 7, 8, 9])

In [ ]:
arr[0]

array([9, 1, 3, 7, 4])

In [ ]:
arr[:2]

array([[9, 1, 3, 7, 4],
       [9, 3, 5, 3, 7]])

In [ ]:
arr[:2,:2]

array([[9, 1],
       [9, 3]])

In [ ]:
arr1=np.random.seed(10)
arr1=np.random.randint(0,10,size=(3,5))
arr1

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0]])

In [ ]:
arr1+arr

array([[18,  5,  3,  8, 13],
       [ 9,  4, 13, 12,  7],
       [13, 15, 11,  5,  4]])

In [ ]:
arr3=np.random.randint(0,20,size=(3,5))
arr3

array([[12,  0, 17, 15, 12],
       [ 8, 10, 13, 11,  1],
       [18, 13,  8,  9,  5]])

In [ ]:
import numpy as np
arr=np.random.seed(100)
arr=np.random.randint(0,100,size=(3,5))
arr

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34]])

In [ ]:
arr1=np.random.seed(100)
arr1=np.random.randint(0,100,size=(3,5))
arr1

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34]])

In [ ]:
arr*arr1

array([[  64,  576, 4489, 7569, 6241],
       [2304,  100, 8836, 2704, 9604],
       [2809, 4356, 9604,  196, 1156]])

In [ ]:
arr-arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
arr**2

array([[  64,  576, 4489, 7569, 6241],
       [2304,  100, 8836, 2704, 9604],
       [2809, 4356, 9604,  196, 1156]])

In [ ]:
np.square(arr)

array([[  64,  576, 4489, 7569, 6241],
       [2304,  100, 8836, 2704, 9604],
       [2809, 4356, 9604,  196, 1156]])

In [ ]:
np.mean(arr)

55.46666666666667

In [ ]:
np.max(arr)

98

In [ ]:
np.min(arr)

8

In [ ]:
np.std(arr)

31.048063099366157

In [ ]:
arr.T

array([[ 8, 48, 53],
       [24, 10, 66],
       [67, 94, 98],
       [87, 52, 14],
       [79, 98, 34]])

In [ ]:
arr1=arr.reshape(3,5,1)
arr1

array([[[ 8],
        [24],
        [67],
        [87],
        [79]],

       [[48],
        [10],
        [94],
        [52],
        [98]],

       [[53],
        [66],
        [98],
        [14],
        [34]]])

In [ ]:
arr.var()

963.9822222222224

In [ ]:
a=np.random.randint(0,10,size=(3,3))
b=np.random.randint(0,10,size=(3,2))
a

array([[1, 5, 3],
       [4, 4, 3],
       [7, 1, 1]])

In [ ]:
b

array([[7, 7],
       [0, 2],
       [9, 9]])

In [ ]:
a.dot(b)  #matrix multiplication dot()=@

array([[34, 44],
       [55, 63],
       [58, 60]])

In [ ]:
c=np.random.randint(0,10,size=(4,3))
c@a

array([[46, 28, 20],
       [12, 44, 27],
       [45, 61, 41],
       [46, 34, 26]])

In [ ]:
c@b

array([[66, 70],
       [56, 58],
       [67, 79],
       [18, 34]])

In [ ]:
a@c.T

array([[28, 13, 43, 46],
       [35, 36, 58, 38],
       [28, 57, 57, 10]])

In [ ]:
e=np.random.randint(0,10,size=(4,3))
e

array([[5, 1, 8],
       [1, 5, 4],
       [2, 8, 3],
       [5, 0, 9]])

In [ ]:
c<e

array([[ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [ ]:
c>=e

array([[False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False]])

In [ ]:
c>7

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False,  True, False]])

In [ ]:
c==6

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
np.sort(c)   #sort elements

array([[2, 3, 5],
       [0, 1, 8],
       [2, 6, 7],
       [0, 2, 8]])

In [ ]:
np.argsort(c) #sort index

array([[1, 0, 2],
       [2, 1, 0],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
np.argmin(c)  #min value

5

In [ ]:
np.argmax(c,axis=1) #max value

array([2, 0, 0, 1])

In [ ]:
c=np.random.randn(10)
c

array([-0.54974619, -0.94004616, -0.82793236,  0.10886347,  0.50780959,
       -0.86222735,  1.24946974, -0.07961125, -0.88973148, -0.88179839])

In [ ]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])